### ISSUE TITLE
Figure 1 in Paper

### ISSUE THREAD

**Issue by FabiPi3** [AI-multimodal/Lightshow#151]
Regarding Figure 1 in the Paper: Claudia asked whether the text could be enlarged? And do we want all items capitalized or not?

**Comment by FCMeng** [comment]
Hi Fabian, I agree that the text could be larger. But I think whether the items being in upper or lower case depend on the module/folder name in lightshow.

**Comment by x94carbone** [comment]
I did this a while ago and forgot to close.
