### ISSUE TITLE
Cannot retrieve data from the Materials Project

### ISSUE THREAD

**Issue by maurov** [AI-multimodal/Lightshow#156]
@x94carbone I am trying to evaluate Lightshow but I am stuck at the first step of building a structure using data from the Materials Project. I always get the following error:

```
MPRestError: REST query returned with error status code 403. Content: b'{"valid_response": false, "error": "API_KEY is not a valid key.", "version": {"db": "2020_09_08", "pymatgen": "2022.0.8", "rest": "2.0"}, "created_at": "2022-11-29T07:57:29.165298"}
```

I have cross-checked my API key and it seems right. Please, do you have any hint how I could solve this?

**Comment by x94carbone** [comment]
@maurov are you using the old or new Materials Project API key? We started building this thing before Materials Project switched to the "new" API, thus for now (until #155 is merged) we're only compatible with the "old" API. 

Sorry for the confusion, this should probably be more well-documented...

**Comment by maurov** [comment]
@x94carbone thank you very much indeed for the prompt reply. Yes, you are right. I was not using the "legacy" version of the API. It works as expected now. Sorry for bothering with such a minor thing.

**Comment by x94carbone** [comment]
@maurov no worries, please feel to bother away! It will help us fix all of the bugs we no doubt have 👍
