### ISSUE TITLE
Size of super cell (VASP/XSpectra) needs to be a parameter

### ISSUE THREAD

**Issue by jtv3** [AI-multimodal/Lightshow#187]
Right now (it seems to me) the supercell is always constructed with a 9Å size, but this should be an adjustable option.

**Comment by matthewcarbone** [comment]
@jtv3 It's not hard-coded, though the docs could be better (sorry)! There's a method, `initialize_supercells`, defined on `Database`.

So the workflow would be:

```python
database = Database.from_materials_project(...)
database.initialize_supercells(YOUR_VALUE_HERE)
```

Let me know if you have any other questions!

**Comment by jtv3** [comment]
I was worried that the problem might be me.

**Comment by matthewcarbone** [comment]
@jtv3 No worries at all! 😊
