### ISSUE TITLE
Strange bug (or maybe non-issue?) with EXCITING

### ISSUE THREAD

**Issue by matthewcarbone** [AI-multimodal/Lightshow#193]
So I'm encountering a weird bug in the tests (I think?) when testing with a structure containing more than just Ti and O. This could be a coincidence and it could happen at any time, but here's the long story short. I'm on commit `ede3d9d`.

```python
from lightshow import Database

# NEW MATERIALS PROJECT API (v2)
database = Database.from_materials_project(material_ids=["mp-754147"])
```

Write the input files and whatnot using standard defaults.

```python
from lightshow import EXCITINGParameters
from lightshow.defaults import EXCITING_DEFAULT_CARDS

mycards = EXCITING_DEFAULT_CARDS
mycards['xs']['BSE']['bsetype'] = 'IP'

exciting_params = EXCITINGParameters(
    cards=mycards,
    edge="K",
    # kpoints=lightshow.common.kpoints.GenericEstimatorKpoints(cutoff=33),
    # nbands=lightshow.common.nbands.UnitCellVolumeEstimate(e_range=40)  
)

database.write("test", options=[exciting_params], absorbing_atoms=["Ti", "O", "Li", "Co"])
```

Now, here's where things get weird. Let's see what the neighbors of site 0 are:

```python
s = database.structures["mp-754147"]
neighbors = s.get_neighbors(s[0], 20)
neighbors = [[xx.nn_distance, str(xx.specie)] for xx in neighbors]
neighbors.sort(key=lambda xx: xx[0])

neighbors[:5]
# [[2.048235442706463, 'O'],
#  [2.073903123716639, 'O'],
#  [2.1057234887497844, 'O'],
#  [2.1289397552271683, 'O'],
#  [2.1518768612671186, 'O']]
```

But now let's read the written `.xml` file and see that that produces...

```python
from pymatgen.io.exciting import ExcitingInput
exciting_s = ExcitingInput.from_file("test/mp-754147/EXCITING/000_Li/input.xml").structure

exciting_neighbors = exciting_s.get_neighbors(exciting_s[0], 20)
exciting_neighbors = [[xx.nn_distance, str(xx.specie)] for xx in exciting_neighbors]
exciting_neighbors.sort(key=lambda xx: xx[0])

exciting_neighbors[:5]
# [[2.090969402260802, 'O'],
#  [2.090969402260803, 'O'],
#  [2.1376486809681263, 'O'],
#  [2.1376486809681268, 'O'],
#  [2.1565877489554155, 'O']]
# ?????
```

It appears something is wrong, right?

Maybe not, because `pymatgen`'s structure matcher code identifies these two structures as identical!

```python

from pymatgen.analysis.structure_matcher import StructureMatcher

matcher = StructureMatcher(primitive_cell=True)
matcher.fit(s, exciting_s)  # returns True

matcher = StructureMatcher(primitive_cell=False)
matcher.fit(s, exciting_s)  # returns True
```

And not just identical, the indexes all match correctly.

```python
transform = matcher.get_transformation(s, exciting_s)
# transform[2] is the index mapping between the two

transform
# (array([[-1, -1,  0],
#         [ 0,  0, -1],
#         [-1,  0,  0]]),
#  array([-0.00617118, -0.49999995,  0.01234225]),
#  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
```

I'm genuinely confused here and have no idea why the neighbors of site 0 are different between these two structures, even though the structures are _identical_ by PMG's own software. Perhaps there's some weird scaling or something that's done in the XML file that wasn't picked up? I have no idea.

@FCMeng @deyulu @vorwerkc @jtv3 @FabiPi3 
who is the EXCITING expert?

**Comment by matthewcarbone** [comment]
@FCMeng No they don't. That's kinda the problem. They appear to be the "same" site in terms of matching the materials together, but my manual analysis with the nearest neighbors doesn't seem to imply that they are...

**Comment by matthewcarbone** [comment]
The thing is, that _none_ of the atoms in the second structure match the nearest-neighbor ordering of the first and I cannot figure out why... but with that said, this is where I almost feel like it's a problem with the test I'm using and not our code. What do you think?

**Comment by FCMeng** [comment]
I don't think I understand it. I was thinking the site 0 in your first and second structure are different. In this way, the nearest-neighbor ordering cannot match with each other by any means. Maybe it is easy to print our the atomic positions for every site in the second structure to see which one matches the site 0 in the first structure?

**Comment by FCMeng** [comment]
I tried play with it a bit. And I found the structure is P1 from MP. But when storing it to local disk, I think pmg tried to discover the space group in the background and converted it to a C2 structure and did all the rescale I think. You can get this by `exciting_s.get_space_group_info()`.  But for vasp when writing to POSCAR, the transformation was not performed. I don't understand why for exciting, there is this transformation happened. I don't understand why after this transformation, the nn distance changed.

**Comment by matthewcarbone** [comment]
Thanks, Fanchen, that's really helpful. Do you have any suggestions here? It's sounding kinda like this is a non-Lightshow-issue, but on the other hand it probably should not be doing any rescaling haha

**Comment by deyulu** [comment]
This looks very confusing. Is the problem only related to exciting .xml
file? @Matthew Carbone ***@***.***> @Fanchen Meng
***@***.***>  When does this step happen exactly, "pmg tried to
discover the space group in the background and converted it to a C2
structure and did all the rescale"?

**Comment by matthewcarbone** [comment]
@deyulu yes it appears to be an issue with the EXCITING xml file only.

**Comment by FabiPi3** [comment]
Can you share the resulting exciting input.xml file with us please?

**Comment by FCMeng** [comment]
@FabiPi3 Just a quick comment: if you only use the EXCITING interface to PMG, e.g. `ExcitingInput(database.structures['mp-754147']).write_file(filename='exciting.xml',celltype="primitive")`, the crystal structure is also transformed.

**Comment by FabiPi3** [comment]
Ok, I checked the pymatgen source code and indeed a transformation happens while writing to file:

```
# determine which structure to use
finder = SpacegroupAnalyzer(self.structure, symprec=symprec, angle_tolerance=angle_tolerance)
if celltype == "primitive":
     new_struct = finder.get_primitive_standard_structure(international_monoclinic=False)
elif celltype == "conventional":
     new_struct = finder.get_conventional_standard_structure(international_monoclinic=False)
elif celltype == "unchanged":
    new_struct = self.structure
else:
    raise ValueError("Type of unit cell not recognized!")
```

I guess @vorwerkc has implemented those lines. I guess you could scrap these lines if you doesn't want the transformation or at least make it optional.

**Comment by FCMeng** [comment]
It seems we may use “celltype ="unchanged"” as the default for exiting writer in lightshow?

**Comment by matthewcarbone** [comment]
I think the default behavior without a doubt must be that the structure in the loaded PMG structure is identical to the saved structure. Do others agree? If nothing else, this makes it consistent with the other methods.

**Comment by deyulu** [comment]
I agree with @Matthew Carbone ***@***.***> on "the structure in
the loaded PMG structure is identical to the saved structure". Consistency
is a key feature to Lightshow. I don't think we can compromise it. --Deyu

**Comment by matthewcarbone** [comment]
@vorwerkc can you hot fix this? Or someone who knows what they're doing with EXCITING.
