### ISSUE TITLE
cannot install using pypy

### ISSUE THREAD

**Issue by FCMeng** [AI-multimodal/Lightshow#194]
I was trying to install Lightshow from pypi. But failed in doing so. The steps are followed.

1. conda create -n lightshow_pypi python
2. source activate lightshow_pypi
3. pip install lightshow

But I got the return 

```
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          #ensure correct shape
          fcoords1, fcoords2 = np.atleast_2d(fcoords1, fcoords2)
      
          pbc = lattice.pbc
          cdef int n_pbc = sum(pbc)
          cdef int n_pbc_im = 3 ** n_pbc
                                ^
      ------------------------------------------------------------
      
      pymatgen/util/coord_cython.pyx:94:26: Cannot assign type 'double' to 'int'
```
Is this related to the python and/or the dependencies versions?

**Comment by matthewcarbone** [comment]
It passes all of the CI tests. What OS are you using? Lightshow isn't tested on Windows, for example.

**Comment by FCMeng** [comment]
I am on a linux system. It's weird.

**Comment by xhqu1981** [comment]
This is not a Lightshow error. As you can see from the error message, it comes from pymatgen. @FCMeng, please check your GCC and header files.

**Comment by FCMeng** [comment]
It seems I cannot install this particular version of pymatgen. I noticed in the dependencies that we are limiting the pymatgen<=2022.7.8, any reason for this? I can install the latest pymatgen.

**Comment by matthewcarbone** [comment]
@FCMeng `lightshow==0.1.3` should work on Linux (or at least ubuntu latest) as it builds correctly in the testing suite. `master` is not up to date though, but I don't think that's your problem.

As @xhqu1981 says, it appears you have a `pymatgen` issue. Maybe your `$PATH` isn't setup correctly and Lightshow is finding the wrong PMG version?

**Comment by FCMeng** [comment]
I installed an older version pymatgen using `pip install pymatgen==2022.5.26`. After that I can install Lightshow using `pip install lightshow`.

**Comment by matthewcarbone** [comment]
That's really strange, especially because `pymatgen==2022.5.26` is semantically "less than" `2022.7.8`. Glad you fixed it but I gotta say it's super strange that your install didn't work. Perhaps it's your version of Python? Lightshow requires python 3.7+ and soon will require 3.9+. Instead of `conda create -n lightshow_pypi python` I would do `conda create -n lightshow_pypi python=3.9` and see if that helps.

**Comment by FCMeng** [comment]
Yes, I tried different versions of python. But this seems not to be the reason. I will close this for now since an older version pymatgen works.

**Comment by matthewcarbone** [comment]
@FCMeng that's so weird. The default installation should require a version-locked PMG... 😁

**Comment by FCMeng** [comment]
@matthewcarbone Yes, the default version of PMG is `<=2022.7.8` and the it tends to install `=2022.7.8`. Therefore, I installed PMG with version `2022.5.26` manually. And then run `pip install lightshow`.

**Comment by matthewcarbone** [comment]
Oh interesting. It could be that for whatever reason now `2022.7.8` is a new release that is failing to be compatible, but `2022.5.26` works.

**Comment by matthewcarbone** [comment]
Very odd though. `0.1.3` does install `pymatgen-2022.7.8` and it works fine in the testing suite...
