### ISSUE TITLE
Add compatibility for molecules and clusters

### ISSUE THREAD

**Issue by matthewcarbone** [AI-multimodal/Lightshow#196]
Currently, Lightshow only accepts structures from disk that can be read via `pymatgen.core.structure.Structure.from_file`. We might want to generalize this to include clusters and molecules. This will be tricky though since some of the calculations in Lightshow are supercell calculations, so it might not be straightforward. Open to suggestions here. @deyulu @FCMeng

**Comment by FCMeng** [comment]
Hi Matt, I remember you did some calculations on molecules with VASP, which I put that part in the fc/v2-molecule branch. Are the results OK? Or can we use the molecule in a large box to do the calculations?

**Comment by matthewcarbone** [comment]
Oh right! Thank you for that. I'll double back to that and try to merge it into `master`.

I think for a molecule or cluster, we need a "large box" to mimic the non-interactiveness whilst still being able to do a supercell calculation.

I think that branch is too outdate for a direct PR, but you're welcome to try. Otherwise I'm just going to cherry pick from it if that's ok with you.

**Comment by FCMeng** [comment]
Sure! Sounds good to me.
