### ISSUE TITLE
Tutorial notebook is broken

### ISSUE THREAD

**Issue by matthewcarbone** [AI-multimodal/Lightshow#252]
@deyulu @FCMeng the tutorial notebook broke along the way at some stage 😁

Basically,

```python
vasp_params_corehole = VASPParameters(
    incar=VASP_INCAR_DEFAULT_COREHOLE_POTENTIAL,
    potcar_directory=None,
    force_spin_unpolarized=False,
    kpoints=lightshow.common.kpoints.GenericEstimatorKpoints(cutoff=43),
    nbands=lightshow.common.nbands.UnitCellVolumeEstimate(e_range=40)
)
```

the default for `force_spin_unpolarized` causes an error when trying to write to disk (because `MAGMOM` isn't in the parameters INCAR file). I think the error is thrown correctly, but should we just change `force_spin_unpolarized` to True in the tutorial so it works?

This also reminds me I have to add smoke tests to the notebooks in our CI loop...

**Comment by FCMeng** [comment]
@matthewcarbone I would like to set the default of `force_spin_unpolarized` to true, as well as in the tutorial. There were some issues @deyulu raised about the magmom.

**Comment by matthewcarbone** [comment]
@FCMeng what do you suggest we change in the tutorial then? Currently it doesn't run 😁

**Comment by FCMeng** [comment]
@matthewcarbone I would like to use True for force_spin_unpolarized. This option works, right?

**Comment by matthewcarbone** [comment]
Should be resolved on latest hotfix to master.

**Comment by deyulu** [comment]
Sorry for the late reply. Setting force_spin_unpolarized to true sounds
good to me.

**Comment by matthewcarbone** [comment]
@deyulu no problem. It's been fixed at this point, thanks!
